name: Trigger Likes

on:
  repository_dispatch:
    types: [trigger-like]

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Call update-likes workflow
        uses: peter-evans/workflow-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_TOKEN }}
          repository: QuQuDeveloppement/mysite
          workflow: update-likes.yml
          ref: main
          inputs:
            id: ${{ github.event.client_payload.id }}
